### ISSUE TITLE
Update the icons

### ISSUE THREAD

**Issue by tony-caffe** [cosinepi/aws-simple-icons-affinity-designer-asset#1]
Hi, I love that you did this for the community as AD cant seem to handle an organized import of SVGs still, sadly. It could easily be a great Visio replacement as well.

Could you update the list from 4 years ago by chance?

**Comment by cosinepi** [comment]
Hi @tony-caffe a newer version provided by @grahamjenson has been uploaded. That is based on the AWS assets from 2020-09. Welcome to give it a try. Pull requests are also welcome.
