### ISSUE TITLE
Updated from Assets 2020-09-11

### ISSUE THREAD

**Issue by grahamjenson** [cosinepi/aws-simple-icons-affinity-designer-asset#2]
I manually updated some of the assets to this years icon set. This is not perfect and not very well grouped, but usable with the asset search.

[AWS-20200911-assets.afassets.zip](https://github.com/cosinepi/aws-simple-icons-affinity-designer-asset/files/5336270/AWS-20200911-assets.afassets.zip)

**Comment by cosinepi** [comment]
Thanks @grahamjenson! I've updated the repo with your version included.
